### ISSUE TITLE
Gossip and Misinformation from someone who doesn't understand boat alternators

### ISSUE THREAD

**Issue by tytower** [FransVeldman/OpenHybridBMS#2]
Quote " the alternator will surge, fry its diodes and destroy all connected equipment in the process. The other charge sources often exibit similar problems when the battery is suddenly disconnected. "

Clearly you have not determined the truth or fallacy of this statement or you are a gossip spreading wowser! . Its a furfy spread by people who want you to buy their expensive gear and it works because people don't know.

Modern Alternators (say Bosch) put out a constant voltage , 14 volts . It does not change no matter what the speed . Only the current varies depending on the state of the battery.
Modern Alternators have up to 16 diodes in them these days to protect them.

I invite you to run your motor and battery system and turn off the battery while the motor is running. You probably often do anyway . I do on petrol cars and diesels. No harm is done whatever.   Its garbage.

**Comment by lithium773** [comment]
And with older alternators? I have a hybrid set up with 200Ah of LA and 120Ah LiFePO4. The alternator is a Mercedes 95A on the first generation Sprinter. So it's 23 years old. So far it has worked fine, but I've never had to charge the Li from a low SoC as solar generally keeps them reasonably charged.

**Comment by rgleason** [comment]
Tytower, what knowing person would do your test? There are enough failed alternater examples in the forums to suggest caution, such that your title is misleading and should be a question!!!

**Comment by tytower** [comment]
Well I would question that . I have not seen failed alternators caused by switching on and off the battery as such . I have seen many examples of alternators being replaced unnecessarily. I've had a few myself before I started to checked them  . Auto electricians have been lying to us for 50 years that I know of. Its a trade that seems to breed fraudsters. They take the old ones and refurbish them and sell them on. Mostly I have found the brushes fail or sometimes the regulator box gets dirty and shorts. The old regulators going back 30 years at least I can say were still all set voltage machines usually set at 13.8 volts . Only lately have they gone to 14 v.

The alternators with separate regulator boxes of old were also set voltage machines but not as accurate.

**Comment by abaeyens** [comment]
Tytower, I'm sorry but what you're saying does not make sense.

- Automotive equipment falls under much more severe regulations than marine equipment. Since a few decades SAE regulations require automotive electronics to be able to tolerate the battery being disconnected (feel free to correct). There is no such requirement for marine systems. Some marine electronics are protected, many are not.
- Some of the protections are sacrificial, aka they can sink the disconnect surge only a few times.
- "Modern Alternators (say Bosch) put out a constant voltage , 14 volts . It does not change no matter what the speed ." Have you ever put an alternator on a test bench and actually measured things? I have, and therefore I can safely state that what you are saying is flat out wrong. In the first place, the alternator regulator system has a bandwidth in the order of a few Hz, far too slow to avoid disconnect surges, which occur in less than a millisecond after disconnect. Second, you'll find that if you connect an alternator to an empty LFP battery that it does not reach 14 V because the internal resistance of the LFP battery is so low that most charging happens in the **current limited** and not voltage limited charge phase. (I base this on the typical alternator and house bank size found on boats). If the regulator tries to reach 14 V anyway, neglecting that current and temperature go far outside the ratings, the alternator simply burns out after a few minutes, if not faster.
- If you read boating forums now and then, you would have seen a story of burnt-out stuff due to a voltage surge passing about every month.

**Comment by rgleason** [comment]
This ISSUE is not an issue and should be closed immediately. 
This is a discussion which should be carried on elsewhere.
Indeed  the title is False and should be changed.
@tytower  Please close this Issue now and start a discussion somewhere.

**Comment by tytower** [comment]
@FransVeldman abaeyens 

If indeed you have had an alternator on a bench and tested it you have not understood it . YOU ALSO CLEARLY DO NOT UNDERSTAND THE RESISTANCE OF LITHIUM BATTERIES.
I invite you to place just one LiFePo4 cell on a test bench .Set the voltage in at 3.65v and turn it on and measure the current . If the state of charge is better than about 30% it will likely take about 2 amps and as the cell voltage comes up that will fall to under an amp at about 3.28v and will continue to fall. 

Before you come back and contradict me make sure you understand that charging process of one cell. Then for 12 v systems there are 4 cells so the top voltage is 14.6v which car alternators cannot reach. Understand that the charge source is at 14 volts with an alternator ,but the plate voltage on the battery can be between 10 volts and 14.2 v approx Put a very low  SOC  on charge and it will almost immediately jump to a plate voltage of over 3 volts and settle at about 3.2 to 3.3 volts for most of the charge time . Its that critical in voltage. Only the beginning and ending "knees" go below or above the voltages quoted here.

Alternators vary the field coil current not the voltage and frequency plays no part here.
You seem to agree that car batteries can be disconnected without harm but you try to separate marine systems that can not. That's rubbish. Car alternators are almost always used in boats.

Nothing is sacrificial in an alternator .That's rubbish

@rgleason  Well thats your opinion. Do you handle all dissent like that?
clearly you only have hearsay knowledge to contribute and do not know anything about alternators or batteries by the sounds of it.

**Comment by rgleason** [comment]
It appears to me that you are talking about perhaps 1% of the alternators being used, and for that reason your statements should not be listened to for a minute. No I have not conducted experiments on my alternator and I am not going to do that. I have read of enough alternator events to convince me that what you are suggesting is not, in fact, the situation for most existing alternators.
Since you wish to create this bogus buried topic in Frans Veldman's github repository, my suggestion to Frans is to simply close the Issue (yes, you can do that.) or delete it.  I am not going to respond again. I am finished with this.

**Comment by tytower** [comment]
Goodo good riddance. You clearly  have no knowledge at all of the subject matter and should just shut up.

**Comment by FransVeldman** [comment]
> Quote " the alternator will surge, fry its diodes and destroy all connected equipment in the process. The other charge sources often exibit similar problems when the battery is suddenly disconnected. "
> 
> Clearly you have not determined the truth or fallacy of this statement or you are a gossip spreading wowser! . Its a furfy spread by people who want you to buy their expensive gear and it works because people don't know.

You have no idea what you are talking about. 

1) Most boat engines are derived from industrial engines, not from cars, and have ditto alternators.
2) Most boats are using older engine types, even the new boats. Why? Because new engines come with electric injection pumps, motor management systems, etc. and these systems are not compatible with a highly corrosive marine environment, not even mentioning the frequent lightning strikes sailboats with their tall masts on open water experience. Take an older "mechanical" engine, and chances are it also lacks a hyper modern CAN-bus capable alternator with all kinds of protection bells and whistles.
3) On sailing boats, the engine is, unlike on cars, not running at the same time when current is being used. Consequently, if the engine is finally running the alternator will have to put a lot of charge in the batteries and is most likely running at full output. To make matters worse, many boats have big alternators, often capable of cranking out more than 100 Amps. Real Amps, not just like in cars where the advertised 100Amp alternator will fry itself if you try to take 100 Amp out of it for more than a few minutes. These big frame alternators are never used on cars. Just suddenly take the load away when the field is fully saturated, and you think you won't see any voltage surge?
4) On many boat alternator, the alternator is regulated by an external regulator, and that regulator has remote sensing wires. Cables are longer, currents are higher: The voltage at the alternator output is no longer the same as the voltage at the battery bank, hence the need for remote sensing wires. Disconnect the main cable and the regulator will crank up the field current to try to see a decent charging voltage, which of course never arrives since the output cable is disconnected. So then the alternator is running with full field current and no load. Still don't see a problem?
5) Are we talking about disconnecting the battery or disconnecting the alternator? In a car that doesn't matter, but on a boat things are different. Where is the big 150 Amp anchor winch in this equation? The electric sail winches? The electric pump for the steering hydraulics? You think you can repeatedly start/stop a 1500 Watt electric motor with huge induction straight from an alternator with no battery in between?

> Modern Alternators (say Bosch) put out a constant voltage , 14 volts.

Again, no clue. Most boats are far from "modern". And on a boat you don't want a constant voltage. The engines are rarely used, but sometimes, unlike a car again, they are running non-stop for multiple days, like when you want to get out of a wind still area on the Pacific. You don't want to keep 14 volts for days on your precious batteries.

> I invite you to run your motor and battery system and turn off the battery while the motor is running. You probably often do anyway . I do on petrol cars and diesels. No harm is done whatever. Its garbage.

No thanks, I have seen plenty of alternators having been destroyed by loose battery cables. It is the most common alternator failure among sailors. Have you any experience and knowledge about boats at all?

**Comment by tytower** [comment]
Yep you too are an ill informed "wowser" of the worse kind.
Its a shame because you waste so much time typing that could be otherwise used profitably. Clot.

**Comment by FransVeldman** [comment]
Clearly @tytower ran out of arguments and resorts to insulting. So I will close the subject now.

**Comment by tytower** [comment]
Clearly @FransVeldman  Does not understand either alternators ,boats or batteries to post such rubbish and now close the discussion because he has not the wits to argue a proper case . While these positions are in the hands of such fools learning takes a back seat and stupidity reigns supreme. I've had 50 years with alternators and batterys but some people won't listen and never learn.
